// AUTO-GENERATED by skinify.py — do not edit manually
window.SKIN = {
  gameTitle:    "Единорог-Стартапер",
  character:    "🦄",
  characterName:"единорога",
  currency:     "⭐",
  currencyName: "звёзд",
  saveKey:      "us_save_v1",
  titles: ["Единорожек-Стажёр", "Единорог-Джуниор", "Единорог-Сеньор", "CTO-Единорог", "Единорог-Основатель", "Единорог-Миллиардер", "Легенда Стартапов 🏆"],
  colors: {
    bg1:     "#1a0828",
    bg2:     "#2a0a40",
    accent:  "#E040FB",
    accent2: "#CE93D8",
  },
};
