// AUTO-GENERATED by skinify.py — do not edit manually
window.SKIN = {
  gameTitle:    "Кот-Предприниматель",
  character:    "🐱",
  characterName:"кота",
  currency:     "🐟",
  currencyName: "рыбок",
  saveKey:      "ce_save_v1",
  titles: ["Котёнок-Стажёр", "Кот-Менеджер", "Директор-Кот", "CEO-Кот", "Кот-Магнат", "Кот-Олигарх", "Легенда Котизма 🏆"],
  colors: {
    bg1:     "#0a1a2e",
    bg2:     "#0d2140",
    accent:  "#4FC3F7",
    accent2: "#81D4FA",
  },
};
