// AUTO-GENERATED by skinify.py — do not edit manually
window.SKIN = {
  gameTitle:    "Пингвин-CEO",
  character:    "🐧",
  characterName:"пингвина",
  currency:     "🧊",
  currencyName: "льдинок",
  saveKey:      "pc_save_v1",
  titles: ["Пингвинёнок", "Пингвин-Менеджер", "Директор-Пингвин", "CEO-Пингвин", "Пингвин-Магнат", "Пингвин-Олигарх", "Ледяной Барон 🏆"],
  colors: {
    bg1:     "#030d1a",
    bg2:     "#061428",
    accent:  "#B3E5FC",
    accent2: "#81D4FA",
  },
};
