// AUTO-GENERATED by skinify.py — do not edit manually
window.SKIN = {
  gameTitle:    "Дракон-Инвестор",
  character:    "🐲",
  characterName:"дракона",
  currency:     "💎",
  currencyName: "кристаллов",
  saveKey:      "di_save_v1",
  titles: ["Дракончик-Стажёр", "Дракон-Трейдер", "Дракон-Директор", "CEO-Дракон", "Дракон-Магнат", "Дракон-Олигарх", "Повелитель Кристаллов 🏆"],
  colors: {
    bg1:     "#0d1a0a",
    bg2:     "#0a2510",
    accent:  "#69F0AE",
    accent2: "#00E676",
  },
};
