// AUTO-GENERATED by skinify.py — do not edit manually
window.SKIN = {
  gameTitle:    "{{GAME_TITLE}}",
  character:    "{{CHARACTER}}",
  characterName:"{{CHARACTER_NAME}}",
  currency:     "{{CURRENCY_ICON}}",
  currencyName: "{{CURRENCY_NAME}}",
  saveKey:      "{{SAVE_KEY}}",
  titles: {{TITLES_JSON}},
  colors: {
    bg1:     "{{COLOR_BG1}}",
    bg2:     "{{COLOR_BG2}}",
    accent:  "{{COLOR_ACCENT}}",
    accent2: "{{COLOR_ACCENT2}}",
  },
};
